services:
  bait:
    build: .
    volumes:
      - ./src:/app
      - /etc/localtime:/etc/localtime:ro
    working_dir: /app
    ports:
      - 8080:8080
    command: ./dev.sh
    restart: unless-stopped
    environment:
      - TZ=Asia/Hong_Kong
    # env_file: ./.env
