// imports.gi.versions.Soup = '2.4';

const { St, GLib, Clutter } = imports.gi;
const Main = imports.ui.main;
const Mainloop = imports.mainloop;

const Soup = imports.gi.Soup;

const Extension = imports.misc.extensionUtils.getCurrentExtension();
// const helloworld = Extension.imports.helloworld;

let panelButton, panelButtonText, timeout;

const url = "https://dummyjson.com/products/1";

const _httpSession = new Soup.SessionAsync();
Soup.Session.prototype.add_feature.call(_httpSession, new Soup.ProxyResolverDefault());

function setButtonText() {
  var arr = [];
  try {
    const message = Soup.Message.new("GET", url);
    message.request_headers.append("X-testing", "testing");
    _httpSession.queue_message(
      message,
      (session, message) => {
        let json = message.response_body.data;
        let data = JSON.parse(json);
        log("/* generated by tools/MakeExchangeData.js */");
        log("const ExchangeData = " + JSON.stringify(data, null, 2) + ";");
        // imports.mainloop.quit("main");
      }
    );
  
    // console.log(Soup);
    // console.log(localWeatherForecastGet());
    _httpSession.queue_message(request, function(httpSession, message) {

    })
    arr.push('hko-weather@louislabs.com');
    panelButtonText.set_text(arr.join(' '));
  } catch (error) {
    console.log(error.message);
  }
  return true;
}

function init() {
  panelButton = new St.Bin({
    style_class: 'panel-button',
  });

  panelButtonText = new St.Label({
    style_class: 'examplePanelTextBlaBlaBla',
    text: 'Starting ...',
    y_align: Clutter.ActorAlign.CENTER,
  });

  panelButton.set_child(panelButtonText);
}

function enable() {
  Main.panel._rightBox.insert_child_at_index(panelButton, 1);
  timeout = Mainloop.timeout_add_seconds(1.0, setButtonText);
}

function disable() {
  Mainloop.source_remove(timeout);
  Main.panel._rightBox.remove_child(panelButton);
}


function getHkoJsonGet(url) {
  var output = { state: 'start', debug: {}, error: '' };
  try {
    

    let sessionSync = new Soup.SessionAsync();

    // https://www.hko.gov.hk/en/abouthko/opendata_intro.htm
    let msg = Soup.Message.new('GET', url);
    sessionSync.send_message(msg);
    res_json = JSON.parse(msg.response_body.data);

    output = { ...output, state: 'done', result: res_json };
  } catch (error) {
    output = { ...output, state: 'error', error: error.message };
    console.error(error.message);
  }

  return output;
}

function localWeatherForecastGet() {
  var test_url_en =
    'https://data.weather.gov.hk/weatherAPI/opendata/weather.php?dataType=flw&lang=en';
  var test_url_tc =
    'https://data.weather.gov.hk/weatherAPI/opendata/weather.php?dataType=flw&lang=tc';

  var output = { state: 'start', debug: {}, error: '' };
  output = getHkoJsonGet(test_url_en);
  output = {...output, debug:{
    test_url_en, test_url_tc,
  }}

  return output;
}
